// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// API keys are loaded from environment variables (--dart-define) at build time.
/// Fallback values are restricted keys with app/bundle restrictions in Google Cloud Console.
///
/// Build command:
/// ```
/// flutter run --dart-define=ANDROID_API_KEY=xxx --dart-define=IOS_API_KEY=xxx
/// ```
class DefaultFirebaseOptions {
  // Read from --dart-define or use restricted fallbacks
  static const String _androidApiKey = String.fromEnvironment(
    'ANDROID_API_KEY',
    defaultValue: 'AIzaSyA5wW6zMHiWB_5xme99MVl0eSj7bhpO-S0',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'IOS_API_KEY',
    defaultValue: 'AIzaSyAS_5VLVEO1GdjrK9XbnqlrHLegMmEGHW4',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:51200928212:android:c0d1e9d964b3213b910e41',
    messagingSenderId: '51200928212',
    projectId: 'huyaka-1809',
    storageBucket: 'huyaka-1809.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:51200928212:ios:1a6411725b0e4a1c910e41',
    messagingSenderId: '51200928212',
    projectId: 'huyaka-1809',
    storageBucket: 'huyaka-1809.firebasestorage.app',
    iosBundleId: 'com.huluca.shopmanager',
  );
}
