// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5wW6zMHiWB_5xme99MVl0eSj7bhpO-S0',
    appId: '1:51200928212:android:fdd5862b241eb527910e41',
    messagingSenderId: '51200928212',
    projectId: 'huyaka-1809',
    storageBucket: 'huyaka-1809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_5VLVEO1GdjrK9XbnqlrHLegMmEGHW4',
    appId: '1:51200928212:ios:04c10eca3b61a3be910e41',
    messagingSenderId: '51200928212',
    projectId: 'huyaka-1809',
    storageBucket: 'huyaka-1809.firebasestorage.app',
    iosBundleId: 'com.huluca.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_5VLVEO1GdjrK9XbnqlrHLegMmEGHW4',
    appId: '1:51200928212:ios:04c10eca3b61a3be910e41',
    messagingSenderId: '51200928212',
    projectId: 'huyaka-1809',
    storageBucket: 'huyaka-1809.firebasestorage.app',
    iosBundleId: 'com.huluca.shop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjeyh1irlquOPS_9NE1LhnQGkGoqNmwZo',
    appId: '1:51200928212:web:12805e998ca77c6a910e41',
    messagingSenderId: '51200928212',
    projectId: 'huyaka-1809',
    authDomain: 'huyaka-1809.firebaseapp.com',
    storageBucket: 'huyaka-1809.firebasestorage.app',
    measurementId: 'G-4C6GFDT31V',
  );

}